server:
  port: 8081
spring:
  application:
    name: spring-boot-server

eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://admin:123456@127.0.0.1:8761/eureka/
  instance:
    # 是否注册 IP 到 eureka server，如不指定或设为 false，那就会注册主机名到 eureka server
    prefer-ip-address: true